### ISSUE TITLE
[Feature] Catalog promotion based on user group 

### ISSUE THREAD

**Issue by Zubis** [Snake-Tn/SyliusCatalogPromotionPlugin#5]
Thanks for this plugin, it's really helpful to show promotions on the catalog.

It might be interesting to display a catalog promotion for a group of users when they are authenticated. In the same way that it is possible to make a promotion on the cart for a user group.

What do you think about this feature?

**Comment by kooliahmd** [comment]
Hey, This feature is a common e-commerce case, and already implemented in [magento 1](http://docs.magento.com/m1/ce/user_guide/marketing/price-rules-catalog.html) 

It's good if we can added to this plugin too, Feel free to contribute here withe a new MR.

**Comment by Zubis** [comment]
I will see to implement it, it will depend on my free time.
I would suggest a PR, maybe someday :)

thanks.
